export enum PieceType {
  Rook = "ROOK",
  Knight = "KNIGHT",
  Bishop = "BISHOP",
  Queen = "QUEEN",
  King = "KING",
  Pawn = "PAWN",
}

export enum PieceDragType {
  WhiteQueenRook = "WHITE_QUEEN_ROOK",
  WhiteQueenKnight = "WHITE_QUEEN_KNIGHT",
  WhiteQueenBishop = "WHITE_QUEEN_BISHOP",
  WhiteQueen = "WHITE_QUEEN",
  WhiteKing = "WHITE_KING",
  WhiteKingBishop = "WHITE_KING_BISHOP",
  WhiteKingKnight = "WHITE_KING_KNIGHT",
  WhiteKingRook = "WHITE_KING_ROOK",
  WhitePawn1 = "WHITE_PAWN_1",
  WhitePawn2 = "WHITE_PAWN_2",
  WhitePawn3 = "WHITE_PAWN_3",
  WhitePawn4 = "WHITE_PAWN_4",
  WhitePawn5 = "WHITE_PAWN_5",
  WhitePawn6 = "WHITE_PAWN_6",
  WhitePawn7 = "WHITE_PAWN_7",
  WhitePawn8 = "WHITE_PAWN_8",

  BlackQueenRook = "BLACK_QUEEN_ROOK",
  BlackQueenKnight = "BLACK_QUEEN_KNIGHT",
  BlackQueenBishop = "BLACK_QUEEN_BISHOP",
  BlackQueen = "BLACK_QUEEN",
  BlackKing = "BLACK_KING",
  BlackKingBishop = "BLACK_KING_BISHOP",
  BlackKingKnight = "BLACK_KING_KNIGHT",
  BlackKingRook = "BLACK_KING_ROOK",
  BlackPawn1 = "BLACK_PAWN_1",
  BlackPawn2 = "BLACK_PAWN_2",
  BlackPawn3 = "BLACK_PAWN_3",
  BlackPawn4 = "BLACK_PAWN_4",
  BlackPawn5 = "BLACK_PAWN_5",
  BlackPawn6 = "BLACK_PAWN_6",
  BlackPawn7 = "BLACK_PAWN_7",
  BlackPawn8 = "BLACK_PAWN_8",
}
