export enum PieceType {
  Rook = "ROOK",
  Knight = "KNIGHT",
  Bishop = "BISHOP",
  Queen = "QUEEN",
  King = "KING",
  Pawn = "PAWN",
}

export enum PieceDragType {
  WhiteQueenRook = "WHITE_QUEEN_ROOK",
  WhiteQueenKnight = "WHITE_QUEEN_KNIGHT",
  WhiteQueenBishop = "WHITE_QUEEN_BISHOP",
  WhiteQueen = "WHITE_QUEEN",
  WhiteKing = "WHITE_KING",
  WhiteKingBishop = "WHITE_KING_BISHOP",
  WhiteKingKnight = "WHITE_KING_KNIGHT",
  WhiteKingRook = "WHITE_KING_ROOK",
  WhitePawnA = "WHITE_PAWN_A",
  WhitePawnB = "WHITE_PAWN_B",
  WhitePawnC = "WHITE_PAWN_C",
  WhitePawnD = "WHITE_PAWN_D",
  WhitePawnE = "WHITE_PAWN_E",
  WhitePawnF = "WHITE_PAWN_F",
  WhitePawnG = "WHITE_PAWN_G",
  WhitePawnH = "WHITE_PAWN_H",

  BlackQueenRook = "BLACK_QUEEN_ROOK",
  BlackQueenKnight = "BLACK_QUEEN_KNIGHT",
  BlackQueenBishop = "BLACK_QUEEN_BISHOP",
  BlackQueen = "BLACK_QUEEN",
  BlackKing = "BLACK_KING",
  BlackKingBishop = "BLACK_KING_BISHOP",
  BlackKingKnight = "BLACK_KING_KNIGHT",
  BlackKingRook = "BLACK_KING_ROOK",
  BlackPawnA = "BLACK_PAWN_A",
  BlackPawnB = "BLACK_PAWN_B",
  BlackPawnC = "BLACK_PAWN_C",
  BlackPawnD = "BLACK_PAWN_D",
  BlackPawnE = "BLACK_PAWN_E",
  BlackPawnF = "BLACK_PAWN_F",
  BlackPawnG = "BLACK_PAWN_G",
  BlackPawnH = "BLACK_PAWN_H",
}

export enum PieceOccupied {
  Ours = "OURS",
  Enemy = "ENEMY",
  None = "NONE",
}
